Session 21/CRM/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('Salesperson');
Route::resource('leads', 'LeadController')->middleware('Admin');
Route::resource('users', 'UserController')->middleware('Admin');

Session 21/CRM/app/Lead.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lead extends Model
{
    //
}

Session 21/CRM/app/Http/Controllers/LeadController.php
<?php

namespace App\Http\Controllers;

use App\Lead;
use Illuminate\Http\Request;
use App\Http\Requests\LeadRequest;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Validator;


class LeadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $leads = Lead::where('status', 1)->get();

        return view('backoffice.leads.index', ['leads' => $leads]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backoffice.leads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LeadRequest $request)
    {
        $lead = new Lead();

        $lead->name = $request->input('name');
        $lead->phone = $request->input('phone');
        $lead->email = $request->input('email');
        $lead->address = $request->input('address');

        $lead->save();
        return redirect()->route('leads.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function show(Lead $lead)
    {
        return view('backoffice.leads.show', ["lead" => $lead]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function edit(Lead $lead)
    {
        return view('backoffice.leads.edit', ["lead" => $lead]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lead $lead)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string',
            'phone' => [
                'required',
                Rule::unique('leads')->ignore($lead)
            ],
            'email' => [
                'email',
                Rule::unique('leads')->ignore($lead)
            ],
            'address' => 'required',
        ]);

        if ($validator->fails()){
            return back()->withErrors($validator);
        }

        $lead->name = $request->input('name');
        $lead->phone = $request->input('phone');
        $lead->email = $request->input('email');
        $lead->address = $request->input('address');

        $lead->save();

        return redirect()->route('leads.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lead $lead)
    {
        $lead->status = false;

        $lead->save();
        return redirect()->route('leads.index');
    }
}

Session 21/CRM/resources/views/backoffice/leads/create.blade.php
@extends('layouts.app')

@section('title', 'Create Lead')

@section('pagename', 'Create New Lead')

@section('content')
    <form action="{{ route('leads.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form-control">
        </div>
        <div class="form-group">
            <label for="phone">Phone</label>
            <input type="tel" name="phone" id="phone" class="form-control">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" id="email" class="form-control">
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" name="address" id="address" class="form-control">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </form>
@endsection

Session 21/CRM/resources/views/backoffice/leads/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Lead')

@section('pagename', 'Edit Lead')

@section('content')
<form action="{{ route('leads.update', $lead) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control" value="{{ $lead->name }}">
    </div>
    <div class="form-group">
        <label for="phone">Phone</label>
        <input type="tel" name="phone" id="phone" class="form-control" value="{{ $lead->phone }}">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" name="email" id="email" class="form-control" value="{{ $lead->email }}">
    </div>
    <div class="form-group">
        <label for="address">Address</label>
        <input type="text" name="address" id="address" class="form-control" value="{{ $lead->address }}">
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>

@endsection

Session 21/CRM/resources/views/backoffice/leads/index.blade.php
@extends('layouts.app')

@section('title', 'Leads')
@section('pagename', 'View All Leads')

@section('content')
<a href="{{ route('leads.create') }}" class="btn btn-success">Add New</a>
<hr>
<table class="table table-bordered">
    <thead>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Actions</th>
    </thead>
    <tbody>
        @foreach($leads as $lead)
            <tr>
                <td>{{ $lead->name }}</td>
                <td>{{ $lead->phone }}</td>
                <td>{{ $lead->email }}</td>
                <td>
                    <a href="{{ route('leads.show', $lead) }}" class="btn btn-primary">Show</a>
                    <a href="{{ route('leads.edit', $lead)}}" class="btn btn-warning">Edit</a>
                    <form style="display: inline-block" action="{{ route('leads.destroy', $lead) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>
@endsection

Session 21/CRM/resources/views/backoffice/leads/show.blade.php
@extends('layouts.app')

@section('title', 'Show Lead')

@section('pagename', 'Show Lead')

@section('content')
    <h2>More information about {{ $lead->name }}</h2>
    <hr>
    <h3><strong>Name: </strong> {{ $lead->name }}</h3>
    <h3><strong>Phone: </strong>{{ $lead->phone }}</h3>
    <h3><strong>Email: </strong>{{ $lead->email }}</h3>
    <h3><strong>Address: </strong>{{ $lead->address }}</h3>
    <hr>
    <div>
        <a href="{{ route('leads.edit', $lead) }}" class="btn btn-warning">Edit</a>
        <form style="display: inline-block" action="{{ route('leads.destroy', $lead) }}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>

@endsection